# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses. The 'type' key defines the base container
# image that will be used to run the application. There is a separate base
# container image for each primary language for the application,
# in multiple versions. Check the PHP documentation
# (https://docs.platform.sh/languages/php.html#supported-versions)
# to find the supported versions for the 'php' type.
type: 'php:8.2'

# The following block defines a single writable directory, 'web/uploads'
# The 'source' specifies where the writable mount is. The 'local' source
# indicates that the mount point will point to a local directory on the
# application container. The 'source_path' specifies the subdirectory
# from within the source that the mount should point at. 
mounts:
  'api/public/uploads':
    source: local
    source_path: uploads
  'api/var/log':
    source: local
    source_path: log
  'api/var/cache':
    source: local
    source_path: cache
  'api/config/jwt':
    source: local
    source_path: jwt

# The size of the persistent disk of the application (in MB).
disk: 2048

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form '<service name>:<endpoint name>'.
relationships:
    postgresdatabase: 'dbpostgres:postgresql'


hooks:
  build: |
    set -x -e
    cd api
    curl -s https://get.symfony.com/cloud/configurator | bash
    COMPOSER_FLAGS="--ignore-platform-reqs" symfony-build
  deploy: |
    set -x -e
    cd api
    symfony-deploy

web:
  locations: 
    '/': 
      root: "api/public"
      passthru: "/index.php"
      allow: true

dependencies:
    php:
        composer/composer: '^1'

runtime:
    extensions:
        - pdo_pgsql