api_platform:
  title: 'API Todo List'
  description: 'API Todo List'
  version: '0.0.1'

  mapping:
    paths: ['%kernel.project_dir%/src/Entity']

  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header