name: Deploy back
 
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: axelerant/platformsh-deploy-action@v1
        with:
          project-id: ${{ secrets.PLATFORM_PROJECT_ID }}
          cli-token: ${{ secrets.PLATFORM_API_TOKEN }}
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
          php-version: 8.1
          force-push: true