name: CI/CD front

on:
  push:
    branches:
      - "main"
      - "dev"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: izemaghilas/platformsh-nodejs-deploy-action@v1.1
        with:
          project-id: ${{ secrets.PLATFORM_PROJECT_ID }}
          cli-token: ${{ secrets.PLATFORM_API_TOKEN }}
          force-push: true
          environment-name: main